### ISSUE TITLE
EIP cannot be bound and reused

### ISSUE THREAD

**Issue by weiwuduzui** [aws-samples/aws-pod-eip-controller#123]
Using the fixed-tag mode, the EIP that has been bound can no longer be bound to the POD after the POD is restarted.

**Comment by turmind** [comment]
I tested it, and if you're referring to the 'kubectl delete pod' method, it is possible to re-associate. In the case of 'kubectl rollout restart', you need to ensure that you have enough idle EIPs with the corresponding tag in your EIP pool to associate with the new pods. If it's not these issues, can you provide more detailed information?

**Comment by jlehtimaki** [comment]
For me this has started to happen more often.
This is the scenario:
1. My pod dies
2. Cannot get loop because "no EIPS can be found"
3. I delete the tags that the `controller` has made
4. Delete the pod again
5. `controller` can now again provision the node an EIP, all is good.

**Comment by turmind** [comment]
@jlehtimaki "My pod dies" would you please clarify the specific situation or how to simulate it?

**Comment by turmind** [comment]
@jlehtimaki I have two questions about the scenario:

```
{"time":"2024-07-21T04:50:35.629798872Z","level":"ERROR","msg":"disassociate address for pod: xxx/xxx-1 fail: disassociate address xxx/xxx-1: disassociate address association-id ","component":"handler"}
```

1. the association-id does not printed in the logs?
2. Does the pod name `xxx/xxx-1` remain unchanged after a restart?

**Comment by jlehtimaki** [comment]
> @jlehtimaki I have two questions about the scenario:
> 
> ```
> {"time":"2024-07-21T04:50:35.629798872Z","level":"ERROR","msg":"disassociate address for pod: xxx/xxx-1 fail: disassociate address xxx/xxx-1: disassociate address association-id ","component":"handler"}
> ```
> 
> 1. the association-id does not printed in the logs?
> 2. Does the pod name `xxx/xxx-1` remain unchanged after a restart? 

1. Only thing that I removed was the pod name + namespace. Replaced with xxx/xxx-1
2. Yes it does. It is a statefulset so the pods dont have any auto generated strings.

**Comment by turmind** [comment]
Determined this is a bug, when the node is released, the delete event of the pod is not captured, and the association of the EIP is released. 
When the Pod is restarted, the controller attempts to release the original association, resulting in failure.

**Comment by jlehtimaki** [comment]
Yes I think this is exactly what's happening when I was checking the code.
Removing some of the tags will resolve the issue.

**Comment by jlehtimaki** [comment]
@turmind are you looking at this or shall I provide a fix for it?

**Comment by turmind** [comment]
> @turmind are you looking at this or shall I provide a fix for it?

Yep, It will be great if you can provide a fix for this.
