### ISSUE TITLE
build with error message

### ISSUE THREAD

**Issue by zjj1002** [aws-samples/aws-pod-eip-controller#50]
MacBook-Pro aws-pod-eip-controller % docker buildx build --tag 073584385202.dkr.ecr.ap-southeast-1.amazonaws.com/aws-pod-eip-controller:latest --platform linux/amd64,linux/arm64 --push .
[+] Building 0.0s (0/0)                                                                                                                  docker:desktop-linux
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/

**Comment by turmind** [comment]
It looks like buildx was not installed successfully. You can refer to https://docs.docker.com/build/architecture/#install-buildx to install it, or refer to https://github.com/docker/buildx#manual-download to manually install it.
