### ISSUE TITLE
Is the IPv4 address of the assigned EIP a random address?

### ISSUE THREAD

**Issue by dongdorrong** [aws-samples/aws-pod-eip-controller#84]
Currently, I'm looking at implementing EKS, where a service called 'A' needs a random public IP and a service called 'B' needs a fixed public IP.

If aws-pod-eip-controller provides a random public IP, I think I can apply it to service 'A'. I am also wondering if it is possible to assign a fixed public IP as well.

I look forward to your response, thank you.

**Comment by turmind** [comment]
aws-pod-eip-controller currently only provides random public IP addresses。

**Comment by dongdorrong** [comment]
@turmind Thank you for checking it out.

**Comment by thehackercat** [comment]
@turmind We have a use case where we utilize fixed Elastic IP addresses in AWS, and we believe that other users may encounter similar situations. In this [PR](https://github.com/aws-samples/aws-pod-eip-controller/pull/92), I have implemented the technical solution to allow users to use both fixed Elastic IP and random Elastic IP modes through annotations.
